<?xml version="1.0" encoding="utf-8"?><Database Name="PlatformDB" Class="LoopcDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=ymhx.loopc.com,143;Initial Catalog=PlatformDB;Persist Security Info=True;User ID=ymhx" SettingsObjectName="Loopc.Repository.Entity.Properties.Settings" SettingsPropertyName="PlatformDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Configuration" Member="Configurations">
    <Type Name="Configuration">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Value" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
    </Type>
  </Table>
</Database>